name: CopperEssentials
version: 0.4.2
main: com.github.tianer2820.copperessentials.CopperEssentials
description: A time saver plugin
author: tianer2820
website: https://github.com/tianer2820/CopperEssentials
api-version: '1.20'

commands:
